const types = {

    GLOBAL_LOADING: '1',
    GLOBAL_ERROR: '2',
    GLOBAL_SUCCESS: '3',

    ENTRY_LOGGED_IN: '102',
    ENTRY_USER_INFO: '103',


    APPNAV_SIDEMENU_OPEN: '201',
    APPNAV_VIEW: '202',
    
    APP_TWITTER_UPDATE: '300',
    APP_ANALYSIS_STATE: '301',
    APP_ONGOING_ANALYSIS: '302',
    APP_GO_BACK_ANALYSIS: '303',
    APP_REPORT_VIEW: '304',
    APP_USER_PROFILE: '305',
    APP_SET_HISTORICAL_DATA: '306',
    APP_ADD_HISTORICAL_DATA: '307',
    APP_SELECT_REPORT: '308',
    APP_UPDATE_SAVE_SETTING: '309',
    APP_SEARCH_DATA_LOADED: '310',
    APP_LOAD_SEARCH_DATA: '311'

};

export default types;
